title: Om
description: AI & Data Science | Research Portfolio

url: "https://omparahd.github.io"
baseurl: ""

theme: minima

title: Om | AI & Data Science

header_pages:
  - blog.md
  - projects.md

markdown: kramdown
kramdown:
  math_engine: mathjax
